python_tests(
    name="test_sources",
    # Globs to pick up all test_*.py in this directory and below
    sources=["**/test_*.py"],
    # If you want certain dependencies or custom settings, list them here:
    dependencies=[
        # "gen_captions/BUILD"
    ],
)
