# BUILD file for the step definitions in tests/features/steps

python_tests(
    name="steps",
    sources=[
        "steps_*.py",
    ]
    # srcs = glob(["*.py"]),
    # Add dependencies as needed, for example:
    # deps = [
    #     "//gen-captions:common",
    # ],
)
