python_requirements(
    name="reqs-dev",
    source="requirements-dev.txt",
)

python_requirements(
    name="reqs-test",
    source="requirements-test.txt",
)

python_requirements(name="reqs", source="requirements.txt")
